language: node_js

node_js:
  - "node"
  - "lts/*"

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

# env:
#   - CXX=g++-4.8

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8
